services:
  app:
    container_name: ${CONTAINER_NAME}
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "${IMAGE_NAME}:${TAG}"
    ports:
      - "${PORT}:80"
      - "${PORT_HTTPS}:443"
      - "${PORT_HTTPS}:443/udp"
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    security_opt:
      - "no-new-privileges=true"
    volumes:
      - ./:/app
    command: sh -c "composer install && frankenphp run"
