services:
  app:
    container_name: php-ci3-oracle
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: "php-ci3-oracle:latest"
    cap_drop:
      - ALL
    security_opt:
      - "no-new-privileges=true"
    volumes:
      - ./:/var/www/html
    command: sh -c "apache2-foreground"
